a=int(input("Enter Number 1 :"))
b=int(input("Enter Number 2 :"))
print("Addition of two numbers is :",a+b)
print("Subtraction of two numbers is :",a-b)
print("Multiplication of two numbers is :",a*b)
print("Division of two numbers is :",a/b)