num1=int(input("Enter Number 1 :"))
num2=int(input("Enter Number 2 :"))
print("-------------------------------------")
print("Addition is : ",num1+num2)
print("Subtraction is : ",num1-num2)
print("Multiplication is :",num1*num2)
print("Division is :",num1/num2)